# Auto-assign configuration
# Automatically add reviewers to pull requests

# Set to true to add reviewers to PRs
addReviewers: true

# Set to true to add assignees to PRs
addAssignees: false

# Number of reviewers to add
numberOfReviewers: 1

# Reviewers to add (will be rotated)
reviewers:
  - gosuperrad

# Skip certain keywords in PR title/branch
skipKeywords:
  - wip
  - draft
  - do-not-review
